name: Deploy Kobweb to GitHub Pages

on:
  push:
    branches: [master]  # or your default branch

permissions:
  contents: write  # needed to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Install Kobweb CLI
        run: ./gradlew :kobwebCli:installDist

      - name: Add Kobweb CLI to PATH
        run: echo "${{ github.workspace }}/kobwebCli/build/install/kobwebCli/bin" >> $GITHUB_PATH

      - name: Build and export Kobweb site
        run: |
          kobweb build -p
          kobweb export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/export